#https://bretahajek.com/2016/11/electron-builder-appveyor-travis-ci-memory-king/


os: unstable
cache:
  - node_modules
environment:
  GH_TOKEN:
      secure: uSMT5r6QFjtDA5W+EhwdHbj8YPsZysgwyGmP7yF7rFJTD5VC/gbaOR0Pu1txNvei
  matrix:
    - nodejs_version: 6
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - node --version
  - npm --version
  - npm test
  - npm run build
  - npm run dist